---
sudo: required
language: objective-c

# Reference for macOS Versions:
# https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
matrix:
  include:
    - os: osx
      osx_image: xcode10.1

before_install:
  - brew update
  - brew install swiftlint
  - brew install vapor/tap/vapor

script:
  - swift build
  - swiftlint --strict
  - swift test